### ISSUE TITLE
:art: 디렉토리 구조 설정 및 entity 추가 

### ISSUE THREAD

**Issue by subin195-09** [PPiing/backend#1]
## 필요 기능
- 디렉토리 구조 설정
- entity 추가

**Comment by jinbekim** [comment]
ercloud entity 보고
skim : 알람, 친구목록
푸팍님: 12시방향 업적이랑 프로필
주팍님: 게임로그
jinbekim: 채팅쪽 3시
만들어서 pr 바랍니다.

**Comment by jinbekim** [comment]
branch `feat-dir-entity-관계명` 으로 브랜치 만들어 주시기 바랍니다.
