### ISSUE TITLE
profile user search시에 seq?가 하나씩 밀리는 문제

### ISSUE THREAD

**Issue by KKWANH** [PPiing/backend#126]
회원가입 후에 `api/users/search/:nickname` 으로 요청시에 아마도 본인의 로우 바로 앞의 로우 데이터가 불러 와지는 오류가 있습니다.

![Image](https://user-images.githubusercontent.com/35485904/179122611-3b2cce5b-6d74-45e5-903f-38faf634e32c.png)

![Image](https://user-images.githubusercontent.com/35485904/179122636-d0c8ecc0-4719-4a9e-ac01-67eb43610fc2.png)

**Comment by jinbekim** [comment]
User entity의 pk가 PrimaryGeneratedColumn이어서 그런것 같은 예상입니다.

**Comment by jinbekim** [comment]
@KKWANH  이거 해결 된거에요?

**Comment by KKWANH** [comment]
> @KKWANH  이거 해결 된거에요?
> @jinbekim 다른 방식으로 해결했습니다! 시퀀스로 검색하는걸로 바꿨어요
