### ISSUE TITLE
:bug: Entity ERDCloud 명세에 맞추기

### ISSUE THREAD

**Issue by joohongpark** [PPiing/backend#13]
## Symptom
- 5월 11일 기준으로 ERCDloud와 일치하지 않는 명세들이 일부 있어 수정이 필요합니다.
  - 일부 명세 테이블과 엔티티명 불일치
  - GameLog 테이블에 불필요한 컬럼
  - ChatParticipants 테이블에 UserSeq 누락 및 관계설정 누락

## Environment (OS / Browser)
- All

**Comment by jinbekim** [comment]
`BaseEntity` 상속 여부 결정

**Comment by jinbekim** [comment]
회의 결과
https://github.com/PPiing/PPoong/discussions/28
