### ISSUE TITLE
:sparkles: 닉네임 생성 시 특수문자 안 되게 하는 규칙 넣어주세요

### ISSUE THREAD

**Issue by KKWANH** [PPiing/backend#194]
## 필요 기능
- 닉네임 변경 등이나 생성을 할 때 / 등의 특수문자를 받지 않고 영/한/숫자 세가짐나 들어가도록 세팅해주세요
- 유저 검색 시 ```users/profile///``` (//가 이름) 식으로 들어가면 404가 뜨는데, 이렇게 검색되는 부분은 프론트에서 막아줄 예정이지만 애초에 닉네임 변경도 이 값으로 할 수 없도록 세팅해주셔야 할 것 같습니다

**Comment by subin195-09** [comment]
@KKWANH 일단 닉네임은 숫자와 영문만 가능하도록 설정해두었습니다 :)
