### ISSUE TITLE
:white_check_mark: Module별로 test케이스 작성.

### ISSUE THREAD

**Issue by jinbekim** [PPiing/backend#22]
## 필요 기능
* module별 테스트 케이스 작성
- [x] #34
- [x] #35
- [x] #55
- [ ] Make Friends module test Cases.
- [ ] Make Alarm module test Cases.

## 연관 기능
- #test, #unitTest, #jest

**Comment by joohongpark** [comment]
HTTP API 추가 프로세스 초안 : https://spring-empress-9c0.notion.site/HTTP-API-f4f5f0d1a7924ee893032658cde8a0aa

**Comment by jinbekim** [comment]
- [ ] Make Game module test Cases.
- [ ] Make Chat module test Cases.
- [ ] Make User module test Cases.
- [ ] Make Friends module test Cases.
- [ ] Make Game module test Cases.
- [ ] Make Alarm module test Cases.
