### ISSUE TITLE
:bug: 알림 기능을 포함한 커뮤니티 기능 문제

### ISSUE THREAD

**Issue by muingY** [PPiing/backend#229]
## Symptom
- 친구추가 요청 수락 혹은 거절 후 새로고침하여 alarm/confirm으로 리스트 받으면 해당 알림이 사라지지 않고 그대로 남음.
- 친구추가 요청 수락시 401...? 떠서 프론트가 로그인화면으로 가버림. 근데 다시 로그인해보면 친구 추가가 되어있음.
- 친구요청 여러번 클릭시 같은 내용의 알림이 다른 알림 seq를 가지고 여러 개의 알림으로 처리됨. (= 중복 친추 알림)
- 중복된 친구요청 알림을 여러번 수락하면 수락한대로 친구 목록의 동일 친구가 여러명으로 뜸.

## Symptom2
- 친구 상대로 프론트 모달을 통해 delete friend 클릭하여 친구삭제 요청시 500 발생. 새로고침해도 친삭 안되어있음. 그런데 상대가 로그인한 페이지에서는 친구목록에 친삭 요청한 친구가 사라져있음.

## Environment (OS / Browser)
- m1, 크롬

**Comment by JAWSP** [comment]
첫번째 증상 고쳤읍니다

**Comment by muingY** [comment]
테스트해보니 아니였따
