### ISSUE TITLE
:sparkles: [status module] make user status

### ISSUE THREAD

**Issue by subin195-09** [PPiing/backend#40]
## 필요 기능
- 유저의 상태가 바뀌었을 때, 소켓을 통해 자신의 상태를 알려주어야 합니다.
- 상태의 종류 : login, game, logout, watch

## 연관 기능
- status module, socket i.o

**Comment by jinbekim** [comment]
이거 닫아도 되나요?

**Comment by subin195-09** [comment]
커밋 좀 더 추가한 후 제가 close 하겠습니다 :)

**Comment by subin195-09** [comment]
[소켓명세](https://github.com/PPiing/wiki/blob/main/develop_backend/status.md)
