### ISSUE TITLE
:sparkles: 로그인 세션 기능 개선

### ISSUE THREAD

**Issue by joohongpark** [PPiing/backend#53]
## 필요 기능
- [x] #57
- [x] #59

## 연관 기능
- 로그인 및 세션

**Comment by jinbekim** [comment]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/59330110/174409583-816419ba-7e61-45f9-966c-9402296f6249.png">
세션관리리 할때 redis를 쓰든 다른 db를 쓰든 디폴트 말고 다른 걸 적용 시켜야 할것 같네요.
