### ISSUE TITLE
nestjs에서 지원하는 typeorm 업그레이드에 따른 메소드 최신화

### ISSUE THREAD

**Issue by jinbekim** [PPiing/backend#71]

**Comment by joohongpark** [comment]
$> npm install -g npm-check-updates
$> ncu -u

쉘에 기입하시면 package.json 업데이트 시켜줍니다.
npm install 기입하시고 충돌나는 코드 조치 해주시면 감사하겠습니다!

**Comment by jinbekim** [comment]
https://github.com/nestjs/nest/releases

@joohongpark 아까 확인을 잘못 했는데 해당 명령어로 의존성 업데이트를 하면
nestjs에서 의존성 지원을 해주지 않는것 같습니다. 
가장 최근 지원 버전은
>https://github.com/nestjs/nest/pull/9301 chore(deps-dev): bump typeorm from 0.2.44 to 0.2.45 ([@dependabot[bot]](https://github.com/apps/dependabot))

입니다.

**Comment by JAWSP** [comment]
https://github.com/PPiing/backend/pull/76

**Comment by JAWSP** [comment]
https://www.inflearn.com/questions/493257
typeorm에서 find, findone메소드부분에서 얼어나는데
요걸 참고하여 바꾸었읍니다
