### ISSUE TITLE
:arrow_up: 사용하고 있는 모듈들을 최신버전으로 업그레이드. typeorm제외

### ISSUE THREAD

**Issue by jinbekim** [PPiing/backend#86]
## 내용
- npm install을 할 경우에 vulnerable 메시지를 띄워 줍니다.
- 하지만 typerom은 업그레이드 할 경우 nestjs에서 지원하지 않아 업데이트 항목에서 제외하는게 좋을것 같습니다.

## 주의점
- 기존과 동일하게 작동하는지 테스트를 해봐야 할것 같습니다.
- 대충 한번 돌려 봤는데 안되는 테스트 케이스가 하나 있습니다. (* 사진참조)
<img width="846" alt="image" src="https://user-images.githubusercontent.com/59330110/175800503-6a08ecdb-3fad-47ff-ae2f-df78cae61e09.png">

**Comment by joohongpark** [comment]
관련해서 제가 한번 확인 후 작업해 볼게요.
nest와 그에 종속된 라이브러리는 nest cli를 이용해서 업데이트를 시도해 보고
nest와 연관이 없는 라이브러리는 latest 버전을 사용하는 식으로 작업해 보겠습니다.
저 테스트 에러 이슈는 아마 jest에서 사용하는 타이머 모킹 관련하여 발생하는거 같은데 확인해 보겠습니다.

**Comment by jinbekim** [comment]
`npm-check-updates`랑 `ncu -u` 쓰니까 금방하긴 하더라구요 ㅎㅎ, 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/59330110/175802812-41c0a4bd-2b9f-47ea-b3d0-395fb2a74af2.png">
typeorm은 `typeorm@0.2.45` 하면 될것 같네요 ㅎ

**Comment by joohongpark** [comment]
ncu와 nest cli 사용하면서 업데이트를 하다 이상한 점을 하나 찾았습니다.
저희가 현재 사용중인 main 브랜치의 `@nestjs/typeorm` 모듈은 8.0.3 버전이며 latest 버전은 8.1.4 입니다.

8.0.3 버전의 `@nestjs/typeorm` 모듈에선 typeORM을 0.2.41 버전을 사용하며
https://github.com/nestjs/typeorm/blob/8.0.3/package.json
latest인 8.1.4 버전의 `@nestjs/typeorm` 모듈에선 typeORM을 0.3.6 버전을 사용합니다.
https://github.com/nestjs/typeorm/blob/8.1.4/package.json

근데 정작 nestjs의 코어 모듈인 `@nestjs/core` 에선 예전 버전 모듈(8.0.0)에선 typeORM을 0.2.34 버전을 사용하며 latest 모듈(8.4.7)에선 0.2.45 버전을 사용하는군요

조금 더 알아보고 코멘트 추가로 남기겠습니다.

**Comment by joohongpark** [comment]
그래서 `@nestjs/typeorm` 도 최신 버전으로 설치하면 에러가 발생하는 상황이기 때문에 (`@nestjs/typeorm` latest와 `@nestjs/core` latest 가 typeorm 모듈에 대해 서로 다른 버전을 원함) typeorm과 연관이 있는 모든 모듈 업데이트는 문제가 없을 때 추후에 다시 진행하는게 좋을거 같군요.
